'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';

interface ExportProps {
  content: string;
  filename?: string;
  format?: 'txt' | 'md' | 'html';
}

export function ExportButton({ content, filename = 'content', format = 'txt' }: ExportProps) {
  const [selectedFormat, setSelectedFormat] = useState<'txt' | 'md' | 'html'>(format);

  const formatContent = (text: string, fmt: 'txt' | 'md' | 'html'): string => {
    switch (fmt) {
      case 'md':
        return `# Generated Content\n\n${text}\n\n---\n*Generated by BrandSpark AI*`;
      case 'html':
        return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Generated Content</title>
  <style>body { font-family: system-ui; max-width: 800px; margin: 0 auto; padding: 20px; }</style>
</head>
<body>
  <h1>Generated Content</h1>
  <p>${text}</p>
  <hr>
  <p><em>Generated by BrandSpark AI</em></p>
</body>
</html>`;
      default:
        return text;
    }
  };

  const handleExport = () => {
    const formatted = formatContent(content, selectedFormat);
    const blob = new Blob([formatted], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename}.${selectedFormat === 'md' ? 'md' : selectedFormat === 'html' ? 'html' : 'txt'}`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex items-center gap-2">
      <select
        value={selectedFormat}
        onChange={(e) => setSelectedFormat(e.target.value as 'txt' | 'md' | 'html')}
        className="text-xs px-2 py-1 rounded border border-slate-200 bg-white"
      >
        <option value="txt">Text</option>
        <option value="md">Markdown</option>
        <option value="html">HTML</option>
      </select>
      <Button onClick={handleExport} variant="outline" size="sm">
        Export
      </Button>
    </div>
  );
}
